<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>docfx-ri</ToolCommandName>
    <PackageId>Documentation.DocfxRemoteInclude.Cli</PackageId>
    <RootNamespace>Docfx.RemoteInclude.Cli</RootNamespace>
    <AssemblyName>docfx-ri</AssemblyName>
    <IsPackable>true</IsPackable>
    <NoWarn>$(NoWarn);NU5111;NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="docfx.app" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Docfx.RemoteInclude\Docfx.RemoteInclude.csproj" />
  </ItemGroup>

</Project>
